server:
  port: 8089
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cadastro
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql
    hibernate.ddl-auto: update
    generate-ddl: true
